### ISSUE TITLE
Working with MRTK 2.8 ?

### ISSUE THREAD

**Issue by SashelI** [LocalJoost/MRTKQuestSeeThrough#1]
Hi,

I was wondering how to make this with MRTK 2.8 ? 
In your article you mention it as working, but I can't have anything else but a black background following the instructions. Your project works fine, but I need MRTK 2.8 and it doesn't have access to MRTK Input, etc. 

Do you have any clues ?

Thanks.

**Comment by LocalJoost** [comment]
Did you follow this example? https://localjoost.github.io/Full-underlay-passthrough-transparency-with-MRTK3-on-Quest-2Pro/ This should work. It worked for me

**Comment by SashelI** [comment]
Thanks, but I managed to make it work by modifying OVRManager.cs : The OVR manager script was destroyed silently while playing, and never replaced. I added a condition in the update method and everything works fine
